CREATE DATABASE RIKKEI_STORE;
USE RIKKEI_STORE;

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(255)
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRICE DECIMAL(10,2),
    STOCK INT,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ORDER_DATE DATETIME,
    STATUS VARCHAR(20),
    TOTAL_MONEY DECIMAL(10,2),
    SHIPPING_ADDRESS VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ORDER_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    PRICE_AT_PURCHASE DECIMAL(10,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO USERS (FULL_NAME, EMAIL, ADDRESS) VALUES
('NGUYEN VAN A', 'A@GMAIL.COM', 'HANOI'),
('TRAN THI B', 'B@GMAIL.COM', 'HCMC'),
('LE VAN C', 'C@GMAIL.COM', 'DANANG'),
('PHAM THI D', 'D@GMAIL.COM', 'HUE'),
('VU VAN E', 'E@GMAIL.COM', 'CAN THO');

INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES 
('ELECTRONICS'), 
('CLOTHING'),
('BOOKS');

INSERT INTO PRODUCTS (CATEGORY_ID, PRODUCT_NAME,PRICE, STOCK) VALUES
(1, 'LAPTOP DELL', 1000.00, 10),
(1, 'IPHONE 15', 800.00, 20),
(2, 'T-SHIRT', 20.00, 100),
(3, 'SQL BOOK', 30.00, 50),
(1, 'MOUSE', 15.00, 200);

INSERT INTO ORDERS (USER_ID, ORDER_DATE, STATUS, SHIPPING_ADDRESS, TOTAL_MONEY) VALUES
(1, NOW(), 'PAID', 'HANOI', 1800.00), 
(2, NOW(), 'PENDING', 'HCMC', 20.00),
(3, NOW(), 'CANCELLED', 'DANANG', 0.00),
(4, NOW(), 'PAID', 'HUE', 30.00),
(1, NOW(), 'PAID', 'HANOI', 1000.00);

INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE_AT_PURCHASE) VALUES
(1, 1, 1, 1000.00),
(1, 2, 1, 800.00),
(2, 3, 1, 20.00),
(3, 4, 1, 30.00),
(4, 5, 2, 15.00),
(5, 1, 1, 1000.00);

-- Q1
SELECT O.ORDER_ID, O.ORDER_DATE, U.FULL_NAME, O.TOTAL_MONEY
FROM ORDERS O
JOIN USERS U ON O.USER_ID = U.USER_ID;

-- Q2 
SELECT * 
FROM PRODUCTS P
JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
WHERE C.CATEGORY_NAME = 'ELECTRONICS';

-- Q3
SELECT USER_ID, FULL_NAME, EMAIL FROM USERS;

-- Q4
SELECT SUM(TOTAL_MONEY) FROM ORDERS;

-- Q5 
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(OD.QUANTITY) TOTAL_QUANTITY
FROM ORDER_DETAILS OD
JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME;

-- Q6 
SELECT OD.PRODUCT_ID, P.PRODUCT_NAME, SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM ORDER_DETAILS OD
JOIN PRODUCTS P ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY OD.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;

-- Q7 
SELECT O.ORDER_ID, U.FULL_NAME, O.TOTAL_MONEY, SUM(OD.QUANTITY) TOTAL_ITEMS
FROM ORDERS O
JOIN USERS U ON O.USER_ID = U.USER_ID
JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY O.ORDER_ID, U.FULL_NAME, O.TOTAL_MONEY;

-- Q8 
SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID NOT IN (
    SELECT PRODUCT_ID FROM ORDER_DETAILS
);

-- Q9 
SELECT U.USER_ID, U.FULL_NAME, COUNT(O.ORDER_ID) TOTAL_ORDERS
FROM USERS U
JOIN ORDERS O ON U.USER_ID = O.USER_ID
GROUP BY U.USER_ID;

-- Q10
SELECT *
FROM PRODUCTS
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS);

-- Q12
SELECT *
FROM ORDERS
ORDER BY TOTAL_MONEY DESC
LIMIT 1;

-- Q15
SELECT *
FROM USERS U
WHERE NOT EXISTS (
    SELECT 1 FROM ORDERS O WHERE O.USER_ID = U.USER_ID
);
